serenity.project.name = SAUCED-EMO
serenity.test.root = org.example

webdriver.driver = chrome
webdriver.chrome.driver=src/test/resources/drivers/chromedriver.exe
webdriver.auto-download = true
serenity.browser.maximized = true

serenity.use.unique.browser = false
serenity.restart.browser.each.scenario = true